name: Fetch Top Wallets (July 2025) + Artifact

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

concurrency:
  group: fetch-top-wallets
  cancel-in-progress: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true

      - name: Sanity checks (script & secrets)
        shell: bash
        run: |
          set -Eeuo pipefail
          # Script must exist
          if [ ! -f "surfpool-backtest/fetch_top_wallets_july.js" ]; then
            echo "ERROR: Missing script at surfpool-backtest/fetch_top_wallets_july.js"
            echo "       (Update the workflow run path or commit the script.)"
            exit 1
          fi
          # Secrets must be present
          if [ -z "${{ secrets.HELIUS_API_KEY_1 }}" ] || [ -z "${{ secrets.HELIUS_API_KEY_2 }}" ]; then
            echo "ERROR: Missing secrets HELIUS_API_KEY_1 and/or HELIUS_API_KEY_2."
            echo "       Add them in: Settings -> Secrets and variables -> Actions."
            exit 1
          fi
          node -v
          echo "Sanity checks passed."

      - name: Create config.july.json from secrets
        shell: bash
        env:
          HELIUS1: ${{ secrets.HELIUS_API_KEY_1 }}
          HELIUS2: ${{ secrets.HELIUS_API_KEY_2 }}
        run: |
          set -Eeuo pipefail
          mkdir -p data
          cat > config.july.json <<'JSON'
          {
            "rpc_urls": [
              "https://mainnet.helius-rpc.com/?api-key=${HELIUS1}",
              "https://mainnet.helius-rpc.com/?api-key=${HELIUS2}"
            ],
            "start_iso": "2025-07-01T00:00:00Z",
            "end_iso":   "2025-07-31T23:59:59Z",
            "max_minutes": 170,
            "page_limit": 1000,
            "per_tx_delay_ms": 250,
            "max_backoff_ms": 8000
          }
          JSON
          # Expand env vars inside JSON
          sed -i "s|\${HELIUS1}|${HELIUS1}|g; s|\${HELIUS2}|${HELIUS2}|g" config.july.json
          echo "Wrote config.july.json (masked keys below):"
          sed 's/api-key=[A-Za-z0-9-]*/api-key=****/g' config.july.json

      - name: Run fetch_top_wallets_july.js
        shell: bash
        timeout-minutes: 330
        run: |
          set -Eeuo pipefail
          # Ensure data dir exists for outputs
          mkdir -p data
          # Run from repo root; script should write to ./data/
          node surfpool-backtest/fetch_top_wallets_july.js 2>&1 | tee data/run.log

      - name: Summarize results (if present)
        if: always()
        shell: bash
        run: |
          echo "=== Files in ./data ==="
          ls -lh data || true
          echo
          echo "=== Top wallets preview (first 20) ==="
          if [ -f data/top_wallets_july.csv ]; then
            head -n 20 data/top_wallets_july.csv
          else
            echo "No top_wallets_july.csv produced."
          fi
          echo
          echo "=== Summary (if any) ==="
          if [ -f data/summary.json ]; then
            cat data/summary.json
          else
            echo "No summary.json found."
          fi

      - name: Upload artifact (all outputs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: top-wallets-july-results
          path: |
            data/**
            config.july.json
          if-no-files-found: warn
          retention-days: 14


